// import { NextResponse } from "next/server";
// import { GoogleGenAI } from "@google/genai";
// import axios from "axios";
// import { courseTable } from "@/config/schema";
// import { eq } from "drizzle-orm";
// import { db } from "@/config/db";

// const PROMPT = `
// Generate detailed HTML content for every topic based on the chapter name and topics. 
// Return valid JSON only.

// Schema:
// {
//   "chapterName": "",
//   "topics": [
//     {
//       "topic": "",
//       "content": "<p>HTML content here</p>"
//     }
//   ]
// }

// User Input:
// `;

// export async function POST(req) {
//   try {
//     const ai = new GoogleGenAI({
//       apiKey: process.env.GEMINI_API_KEY,
//     });

//     const { course, courseTitle, courseId } = await req.json();
//     const chapters = course?.chapters || [];

//     const promises = chapters.map(async (chapter) => {
//       const prompt = PROMPT + JSON.stringify(chapter);

//       // ---------------- AI CALL ----------------
//       const response = await ai.models.generateContent({
//         model: "gemini-2.5-flash-lite",
//         contents: [
//           {
//             role: "user",
//             parts: [{ text: prompt }],
//           },
//         ],
//       });

//       const text =
//         response.candidates?.[0]?.content?.parts?.[0]?.text || "{}";

//       const cleaned = text
//         .replace("```json", "")
//         .replace("```", "")
//         .trim();

//       let jsonResp;

//       try {
//         jsonResp = JSON.parse(cleaned);
//       } catch (err) {
//         console.error("JSON Parse Error → ", cleaned);
//         throw new Error("Invalid JSON generated by Gemini");
//       }

//       // ---------------- YOUTUBE VIDEOS ----------------
//       const youtubeData = await GetYouTubeVideos(chapter?.chapterName);

//       return {
//         chapterName: chapter.chapterName,
//         courseData: jsonResp,
//         youtubeVideos: youtubeData,
//       };
//     });

//     const CourseContent = await Promise.all(promises);

//     // save to db
//     const dbResponse = await db.update(courseTable).set({
//         courseContent:CourseContent
//     }).where(eq(courseTable.cid,courseId))


//     return NextResponse.json({
//       courseName: courseTitle,
//       courseId,
//       courseContent: CourseContent,
//     });
//   } catch (error) {
//     console.error("SERVER ERROR:", error);
//     return NextResponse.json(
//       { error: error.message },
//       { status: 500 }
//     );
//   }
// }


// // -------------------------------------
// // YOUTUBE API FUNCTION
// // -------------------------------------
// const YOUTUBE_BASE_URL = "https://www.googleapis.com/youtube/v3/search";

// const GetYouTubeVideos = async (topic) => {
//   try {
//     const params = {
//       part: "snippet",
//       q: topic,
//       maxResults: 4,
//       type: "video",
//       key: process.env.YOUTUBE_API_KEY,
//     };

//     const resp = await axios.get(YOUTUBE_BASE_URL, { params });
//     const youtubeVideoListResp =resp.data.items;
//     const youtubeVideoList=[];
//     youtubeVideoListResp.forEach(item=>{
//         const data={
//             videoId:item.id?.videoId,
//             title:item?.snippet?.title
//         }
//         youtubeVideoList.push(data);
//     })
//     console.log("youtubeVideoList : ",youtubeVideoList)
//     return youtubeVideoList ;
//   } catch (err) {
//     console.error("YouTube Fetch Error:", err);
//     return [];
//   }
// };


// // import { NextResponse } from "next/server"
// // import {ai} from "../generate-course-layout/route"

// // const PROMPT = `Depends on Chapter name and Topic Generate content for each topic in HTMl and give response in JSON format.
// // Schema:{
// // chapterName:<>,
// // {
// // topic:<>,
// // content:<>
// // }
// // }
// // :User Input:
// // `

// // export async function POST(req){
// //     const ai = new GoogleGenAI({
// //           apiKey: process.env.GEMINI_API_KEY,
// //         });
// //     const {course,courseTitle,courseId} = await req.json()
// //     const promises = courseJson?.chapters?.map(async(chapter)=>{
// //         const config = {
// //             responseMimeType : 'text/plain',
// //         };
// //         const model = 'gemini-2.0-flash';
// //         const contents =[
// //             {
// //                 role:'user',
// //                 parts:[
// //                     {
// //                         text:PROMPT+JSON.stringify(chapter),
// //                     },
// //                 ],
// //             },
// //         ]
// //         const response = await ai.models.generateContent({
// //             model,
// //             config,
// //             contents,
// //         })
// //         console.log(response.candidates?.[0]?.content?.parts?.[0]?.text || "No response");
// //          const RawJson = RawResp.replace('```json','').replace('```','');
// //     const JSONResp = JSON.parse(RawJson);
// //     //GET Youtube Videos

// //     return JSONResp
// //     })

// //     const CourseContent = await Promise.all(promises)
// //     return NextResponse.json(
// //         {
// //             courseName:courseTitle,
// //             CourseContent:CourseContent
// //         }
// //     )
// // }


// // import { NextResponse } from "next/server";
// // import { GoogleGenAI } from "@google/genai";
// // import axios from "axios";
// // import { courseTable } from "@/config/schema";
// // import { eq } from "drizzle-orm";
// // import { db } from "@/config/db";

// // const PROMPT = `
// // Generate detailed HTML content for every topic based on the chapter name and topics.
// // Return VALID JSON ONLY.

// // Schema:
// // {
// //   "chapterName": "",
// //   "topics": [
// //     {
// //       "topic": "",
// //       "content": "<p>HTML content</p>"
// //     }
// //   ]
// // }

// // User Input:
// // `;

// // export async function POST(req) {
// //   try {
// //     const { courseId } = await req.json();

// //     if (!courseId) {
// //       return NextResponse.json(
// //         { error: "courseId is required" },
// //         { status: 400 }
// //       );
// //     }

// //     /* ---------- FETCH COURSE ---------- */
// //     const courseResult = await db
// //       .select()
// //       .from(courseTable)
// //       .where(eq(courseTable.cid, courseId));

// //     const course = courseResult?.[0];

// //     if (!course) {
// //       return NextResponse.json(
// //         { error: "Course not found" },
// //         { status: 404 }
// //       );
// //     }

// //     /* ---------- CACHE CHECK ---------- */
// //     if (
// //       course.courseContent &&
// //       Object.keys(course.courseContent).length > 0
// //     ) {
// //       return NextResponse.json({
// //         courseId,
// //         courseContent: course.courseContent,
// //         cached: true,
// //       });
// //     }

// //     const chapters = course.courseJson?.course?.chapters || [];

// //     if (chapters.length === 0) {
// //       return NextResponse.json(
// //         { error: "No chapters found" },
// //         { status: 400 }
// //       );
// //     }

// //     /* ---------- GEMINI ---------- */
// //     const ai = new GoogleGenAI({
// //       apiKey: process.env.GEMINI_API_KEY,
// //     });

// //     const courseContent = [];

// //     for (const chapter of chapters) {
// //       const prompt = PROMPT + JSON.stringify(chapter);

// //       let rawText = "{}";

// //       try {
// //         const response = await ai.models.generateContent({
// //           model: "gemini-2.5-flash-lite",
// //           contents: [
// //             {
// //               role: "user",
// //               parts: [{ text: prompt }],
// //             },
// //           ],
// //         });

// //         rawText =
// //           response?.candidates?.[0]?.content?.parts?.[0]?.text || "{}";
// //       } catch (err) {
// //         if (err?.status === 429) {
// //           return NextResponse.json(
// //             { error: "Gemini quota exceeded" },
// //             { status: 429 }
// //           );
// //         }
// //         throw err;
// //       }

// //       const cleaned = rawText
// //         .replace(/```json/gi, "")
// //         .replace(/```/g, "")
// //         .trim();

// //       let chapterContent;
// //       try {
// //         chapterContent = JSON.parse(cleaned);
// //       } catch (err) {
// //         console.error("Invalid JSON:", cleaned);
// //         throw new Error("Gemini returned invalid JSON");
// //       }

// //       /* ---------- YOUTUBE ---------- */
// //       const youtubeVideos = await getYouTubeVideos(
// //         chapter.chapterName
// //       );

// //       courseContent.push({
// //         chapterName: chapter.chapterName,
// //         duration: chapter.duration,
// //         content: chapterContent,
// //         youtubeVideos,
// //       });
// //     }

// //     /* ---------- SAVE ---------- */
// //     await db
// //       .update(courseTable)
// //       .set({ courseContent })
// //       .where(eq(courseTable.cid, courseId));

// //     return NextResponse.json({
// //       courseId,
// //       courseContent,
// //     });
// //   } catch (error) {
// //     console.error("🔥 SERVER ERROR:", error);
// //     return NextResponse.json(
// //       { error: error.message },
// //       { status: 500 }
// //     );
// //   }
// // }

// // /* ---------------------------------- */
// // /* YOUTUBE API */
// // /* ---------------------------------- */

// // const YOUTUBE_BASE_URL =
// //   "https://www.googleapis.com/youtube/v3/search";

// // async function getYouTubeVideos(topic) {
// //   try {
// //     const params = {
// //       part: "snippet",
// //       q: topic,
// //       maxResults: 4,
// //       type: "video",
// //       key: process.env.YOUTUBE_API_KEY,
// //     };

// //     const resp = await axios.get(YOUTUBE_BASE_URL, { params });

// //     return (
// //       resp.data?.items?.map((item) => ({
// //         videoId: item.id?.videoId,
// //         title: item.snippet?.title,
// //       })) || []
// //     );
// //   } catch (err) {
// //     console.error("YouTube error:", err.message);
// //     return [];
// //   }
// // }


import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import axios from "axios";
import { courseTable } from "@/config/schema";
import { eq } from "drizzle-orm";
import { db } from "@/config/db";

/* ---------------- PROMPT ---------------- */
const PROMPT = `
Generate detailed HTML content for every topic based on the chapter name and topics.
Return ONLY valid JSON.
Do not include explanations, markdown, or extra text.

Schema:
{
  "chapterName": "string",
  "topics": [
    {
      "topic": "string",
      "content": "<p>HTML content</p>"
    }
  ]
}

User Input:
`;

/* ---------------- UTILS ---------------- */
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const extractJSON = (text) => {
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start === -1 || end === -1) return null;

  try {
    return JSON.parse(text.slice(start, end + 1));
  } catch {
    return null;
  }
};

/* ---------------- API ---------------- */
export async function POST(req) {
  try {
    const ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
    });

    const { course, courseTitle, courseId } = await req.json();
    const chapters = course?.chapters || [];

    const courseContent = [];

    for (const chapter of chapters) {
      const prompt = PROMPT + JSON.stringify(chapter);

      let rawText = "";

      try {
        const response = await ai.models.generateContent({
          model: "gemini-2.5-flash-lite",
          contents: [
            {
              role: "user",
              parts: [{ text: prompt }],
            },
          ],
        });

        rawText =
          response?.candidates?.[0]?.content?.parts?.[0]?.text || "";
      } catch (err) {
        if (err?.status === 429) {
          console.error("⚠ Gemini rate limit hit");
          break;
        }
        console.error("Gemini Error:", err);
        continue;
      }

      const parsedJSON = extractJSON(rawText);

      if (!parsedJSON) {
        console.error("❌ Invalid JSON from Gemini:", rawText);
        continue; // skip this chapter safely
      }

      const youtubeVideos = await getYouTubeVideos(
        chapter.chapterName
      );

      courseContent.push({
        chapterName: chapter.chapterName,
        duration: chapter.duration,
        courseData: parsedJSON,
        youtubeVideos,
      });

      // prevent 429
      await sleep(2500);
    }

    // save partial or full content
    await db
      .update(courseTable)
      .set({ courseContent })
      .where(eq(courseTable.cid, courseId));

    return NextResponse.json({
      courseName: courseTitle,
      courseId,
      courseContent,
    });
  } catch (error) {
    console.error("SERVER ERROR:", error);
    return NextResponse.json(
      { error: error.message },
      { status: 500 }
    );
  }
}

/* ---------------- YOUTUBE ---------------- */
const YOUTUBE_BASE_URL =
  "https://www.googleapis.com/youtube/v3/search";

const getYouTubeVideos = async (topic) => {
  try {
    const resp = await axios.get(YOUTUBE_BASE_URL, {
      params: {
        part: "snippet",
        q: topic,
        maxResults: 4,
        type: "video",
        key: process.env.YOUTUBE_API_KEY,
      },
    });

    return resp.data.items.map((item) => ({
      videoId: item.id?.videoId,
      title: item.snippet?.title,
    }));
  } catch (err) {
    console.error("YouTube Fetch Error:", err);
    return [];
  }
};
