import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";
import axios from "axios";
import { courseTable } from "@/config/schema";
import { eq } from "drizzle-orm";
import { db } from "@/config/db";

const PROMPT = `
Generate detailed HTML content for every topic based on the chapter name and topics. 
Return valid JSON only.

Schema:
{
  "chapterName": "",
  "topics": [
    {
      "topic": "",
      "content": "<p>HTML content here</p>"
    }
  ]
}

User Input:
`;

export async function POST(req) {
  try {
    const ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
    });

    const { course, courseTitle, courseId } = await req.json();
    const chapters = course?.chapters || [];

    const promises = chapters.map(async (chapter) => {
      const prompt = PROMPT + JSON.stringify(chapter);

      // ---------------- AI CALL ----------------
      const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: [
          {
            role: "user",
            parts: [{ text: prompt }],
          },
        ],
      });

      const text =
        response.candidates?.[0]?.content?.parts?.[0]?.text || "{}";

      const cleaned = text
        .replace("```json", "")
        .replace("```", "")
        .trim();

      let jsonResp;

      try {
        jsonResp = JSON.parse(cleaned);
      } catch (err) {
        console.error("JSON Parse Error → ", cleaned);
        throw new Error("Invalid JSON generated by Gemini");
      }

      // ---------------- YOUTUBE VIDEOS ----------------
      const youtubeData = await GetYouTubeVideos(chapter?.chapterName);

      return {
        chapterName: chapter.chapterName,
        courseData: jsonResp,
        youtubeVideos: youtubeData,
      };
    });

    const CourseContent = await Promise.all(promises);

    // save to db
    const dbResponse = await db.update(courseTable).set({
        courseContent:CourseContent
    }).where(eq(courseTable.cid,courseId))


    return NextResponse.json({
      courseName: courseTitle,
      courseId,
      courseContent: CourseContent,
    });
  } catch (error) {
    console.error("SERVER ERROR:", error);
    return NextResponse.json(
      { error: error.message },
      { status: 500 }
    );
  }
}


// -------------------------------------
// YOUTUBE API FUNCTION
// -------------------------------------
const YOUTUBE_BASE_URL = "https://www.googleapis.com/youtube/v3/search";

const GetYouTubeVideos = async (topic) => {
  try {
    const params = {
      part: "snippet",
      q: topic,
      maxResults: 4,
      type: "video",
      key: process.env.YOUTUBE_API_KEY,
    };

    const resp = await axios.get(YOUTUBE_BASE_URL, { params });
    const youtubeVideoListResp =resp.data.items;
    const youtubeVideoList=[];
    youtubeVideoListResp.forEach(item=>{
        const data={
            videoId:item.id?.videoId,
            title:item?.snippet?.title
        }
        youtubeVideoList.push(data);
    })
    console.log("youtubeVideoList : ",youtubeVideoList)
    return youtubeVideoList ;
  } catch (err) {
    console.error("YouTube Fetch Error:", err);
    return [];
  }
};


// import { NextResponse } from "next/server"
// import {ai} from "../generate-course-layout/route"

// const PROMPT = `Depends on Chapter name and Topic Generate content for each topic in HTMl and give response in JSON format.
// Schema:{
// chapterName:<>,
// {
// topic:<>,
// content:<>
// }
// }
// :User Input:
// `

// export async function POST(req){
//     const ai = new GoogleGenAI({
//           apiKey: process.env.GEMINI_API_KEY,
//         });
//     const {course,courseTitle,courseId} = await req.json()
//     const promises = courseJson?.chapters?.map(async(chapter)=>{
//         const config = {
//             responseMimeType : 'text/plain',
//         };
//         const model = 'gemini-2.0-flash';
//         const contents =[
//             {
//                 role:'user',
//                 parts:[
//                     {
//                         text:PROMPT+JSON.stringify(chapter),
//                     },
//                 ],
//             },
//         ]
//         const response = await ai.models.generateContent({
//             model,
//             config,
//             contents,
//         })
//         console.log(response.candidates?.[0]?.content?.parts?.[0]?.text || "No response");
//          const RawJson = RawResp.replace('```json','').replace('```','');
//     const JSONResp = JSON.parse(RawJson);
//     //GET Youtube Videos

//     return JSONResp
//     })

//     const CourseContent = await Promise.all(promises)
//     return NextResponse.json(
//         {
//             courseName:courseTitle,
//             CourseContent:CourseContent
//         }
//     )
// }